# Generated by Django 3.0 on 2019-12-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=200)),
                ('nomor_telp', models.CharField(max_length=13)),
                ('jabatan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MataPelajarn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelajaran', models.CharField(max_length=200)),
                ('jadwal_dimulai', models.TimeField(verbose_name='date_published')),
                ('jadwal_berakhir', models.TimeField(verbose_name='date_published')),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=200)),
                ('nomor_telp', models.CharField(max_length=13)),
                ('nomor_absen', models.CharField(max_length=50)),
                ('nilai_rata', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=200)),
                ('nomor_telp', models.CharField(max_length=13)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ata.MataPelajarn')),
            ],
        ),
        migrations.CreateModel(
            name='LiveCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_live_code', models.CharField(max_length=200)),
                ('banyak_soal', models.IntegerField(default=0)),
                ('bobot_nilai', models.CharField(max_length=10)),
                ('tanggal_pelaksanaan', models.DateTimeField(verbose_name='date_published')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ata.MataPelajarn')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_challenge', models.CharField(max_length=200)),
                ('banyak_soal', models.IntegerField(default=0)),
                ('bobot_nilai', models.CharField(max_length=10)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ata.MataPelajarn')),
            ],
        ),
    ]
